import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Menu from "./_components/menu";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="m-auto mt-6">
          <Menu />
        </div>
        <div className="m-aut py-10">{children}</div>
      </body>
    </html>
  );
}
